/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-west-1",
  "aws_cognito_identity_pool_id": "us-west-1:c9bb2542-b1ef-4d1b-a821-745ed84c8db8",
  "aws_cognito_region": "us-west-1",
  "aws_user_pools_id": "us-west-1_jJ8qtzkbJ",
  "aws_user_pools_web_client_id": "7g9l246gdh53nfk7l2m4sn4ft2",
  "oauth": {},
  "aws_cognito_username_attributes": [],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
      "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
      "SMS"
  ],
  "aws_cognito_password_protection_settings": {
      "passwordPolicyMinLength": 8,
      "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
      "EMAIL"
  ],
  "aws_appsync_graphqlEndpoint": "https://fu7r4zuqs5f6lhsch3qleveup4.appsync-api.us-west-1.amazonaws.com/graphql",
  "aws_appsync_region": "us-west-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": "da2-y5nta5akx5b6lmvgt74tv45cwq"
};


export default awsmobile;